### ISSUE TITLE
HTTP error code 500

### ISSUE THREAD

**Issue by dgodfather** [piplongrun/4tube.bundle#3]
I get this for anywhere a video exists. Probably has to do with the new video player.

**Comment by piplongrun** [comment]
Nope, nothing to do with new video player... URL service still works as expected. I did do a small update on the channel code just now, but I don't think this is related. Reopen and post log files (`com.plexapp.plugins.4tube.log` and `com.plexapp.system.log`) from just after the error happened for me to look into.
